ccflags-y += -Itechpack/camera-legacy-n/
ccflags-y += -Itechpack/camera-legacy-n/common
ccflags-y += -Itechpack/camera-legacy-n/sensor
ccflags-y += -Itechpack/camera-legacy-n/sensor/cci
ccflags-y += -Idrivers/misc/
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o msm_camera_tz_i2c.o
