ccflags-y += -Itechpack/camera-legacy-n
ccflags-y += -Itechpack/camera-legacy-n/common
ccflags-y += -Itechpack/camera-legacy-n/sensor/io
ccflags-y += -Itechpack/camera-legacy-n/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
