ccflags-y += -Itechpack/camera-legacy-n
ccflags-y += -Itechpack/camera-legacy-n/isp/
ccflags-y += -Itechpack/camera-legacy-n/sensor/io
ccflags-y += -Itechpack/camera-legacy-n/common
ccflags-y += -Itechpack/camera-legacy-n/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
